### ISSUE TITLE
Add some further examples to the repo

### ISSUE THREAD

**Issue by gtfisher** [chaostoolkit-incubator/kubernetes-crd#36]
Add an example to the repo to show the use of env variables as part of the ConfigMap.
Add an example to the repo to show how to run from URL.

**Comment by dmartin35** [comment]
fixed by commits
- https://github.com/chaostoolkit-incubator/kubernetes-crd/commit/a7e33c5bc5c3b201e300895b88738745cc9c0a4c
- https://github.com/chaostoolkit-incubator/kubernetes-crd/commit/c3224f8f41e0ed488b411119bdabfac4d2648b76

closing this issue
