### ISSUE TITLE
Settings.yaml file does not exist, dead link in readme

### ISSUE THREAD

**Issue by TGPSKI** [chaostoolkit-incubator/kubernetes-crd#56]
The repository readme mentions a `settings.yaml` file. However, this file does not resolve, and there is no definition of what should be inside of this file. 

![image](https://user-images.githubusercontent.com/12532803/85471876-ef56f800-b565-11ea-8795-ff441f4549df.png)

**Comment by jacobscunn07** [comment]
I am also looking for what the settings file should look like...

**Comment by dmartin35** [comment]
Thanks @TGPSKI good catch !

**Comment by dmartin35** [comment]
@jacobscunn07 You'll find more details about the CTK settings file in the official doc 
https://docs.chaostoolkit.org/reference/usage/cli/#configure-the-chaos-toolkit
but for basic use cases you probably don't need to override/customize these settings

**Comment by dmartin35** [comment]
fixed link to CTK doc issue by PR #66 ; closing this issue; feel free guys to re-open/ask questions if this is not enough.

**Comment by jacobscunn07** [comment]
Thanks @dmartin35. You're right, I probably won't need to override many settings, but I was looking for how to configure the slack notifications. At a quick glance, it looks like the docs have that info now. Thanks! 🥳
