### ISSUE TITLE
Operator does not run with an experiment on YAML format?

### ISSUE THREAD

**Issue by bbarin** [chaostoolkit-incubator/kubernetes-crd#71]
It's more a question than an issue. Does the operator allows create a config map with an experiment based on a YAML?
I've tried and it fails because it tries to parse the file as JSON. Is there any parameter am I missing to allow it?
I've looked at the CRD and it hardcodes experiment.json as a mapped file.

**Comment by Lawouach** [comment]
Hello,

Good question. we could certainly support both indeed.

**Comment by Lawouach** [comment]
Hopefully supported in https://github.com/chaostoolkit-incubator/kubernetes-crd/commit/1bd319b7ec057b70f7857fb2639638930d434c71

**Comment by Lawouach** [comment]
This has not been released yet.
